/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rocks_pizzaandcoffee_mangofmt_LibMango */

#ifndef _Included_rocks_pizzaandcoffee_mangofmt_LibMango
#define _Included_rocks_pizzaandcoffee_mangofmt_LibMango
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rocks_pizzaandcoffee_mangofmt_LibMango
 * Method:    new_mango_file
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_rocks_pizzaandcoffee_mangofmt_LibMango_new_1mango_1file
  (JNIEnv *, jclass);

/*
 * Class:     rocks_pizzaandcoffee_mangofmt_LibMango
 * Method:    mangofile_save
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_rocks_pizzaandcoffee_mangofmt_LibMango_mangofile_1save
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
