/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rocks_pizzaandcoffee_mangofmt_LibMango */

#ifndef _Included_rocks_pizzaandcoffee_mangofmt_LibMango
#define _Included_rocks_pizzaandcoffee_mangofmt_LibMango
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rocks_pizzaandcoffee_mangofmt_LibMango
 * Method:    new_mango_file
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_rocks_pizzaandcoffee_mangofmt_LibMango_new_1mango_1file
  (JNIEnv *, jclass);

/*
 * Class:     rocks_pizzaandcoffee_mangofmt_LibMango
 * Method:    mangofile_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_rocks_pizzaandcoffee_mangofmt_LibMango_mangofile_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     rocks_pizzaandcoffee_mangofmt_LibMango
 * Method:    mangofile_save
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_rocks_pizzaandcoffee_mangofmt_LibMango_mangofile_1save
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     rocks_pizzaandcoffee_mangofmt_LibMango
 * Method:    mangofile_add_image_by_path
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_rocks_pizzaandcoffee_mangofmt_LibMango_mangofile_1add_1image_1by_1path
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     rocks_pizzaandcoffee_mangofmt_LibMango
 * Method:    mangofile_image_count
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_rocks_pizzaandcoffee_mangofmt_LibMango_mangofile_1image_1count
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
